name: riniel_chat
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+2

environment:
  sdk: ^3.10.0

dependencies:
  bloc: ^9.0.1
  bloc_concurrency: ^0.3.0
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flex_color_picker: ^3.7.1
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.4
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  meta: ^1.16.0
  cross_file: ^0.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/

  uses-material-design: true
